- name: Removing old cluster
  command:
    kubeadm reset --force
  register: kubeadm_reset

- name: Initializing the k8s cluster
  command:
    kubeadm init
  register: kubeadm_init

- name: Creating the directory .kube
  file:
    path: ~/.kube
    state: directory

- name: Linking the admin.conf file to the ~/.kube/config
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link

- name: Configuring the pod Weavenet network
  shell: kubectl apply -f {{ default_url_weavenet }}
  register: weavenet_result

- name: Getting the token to add workers to the cluster
  shell: kubeadm token list | cut -d ' ' -f1 | sed -n '2p'
  register: k8s_token

- name: CA Hash
  shell: openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  register: k8s_master_ca_hash

- name: Adding the token and hash in a dummy host
  add_host:
    name: "K8S_TOKEN_HOLDER"
    token: "{{ k8s_token.stdout }}"
    hash: "{{ k8s_master_ca_hash.stdout }}"

- name:
  debug:
    msg: "[MASTER] K8S_TOKEN_HOLDER - O token eh {{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"

- name:
  debug:
    msg: "[MASTER] K8S_TOKEN_HOLDER - O hash eh {{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}"
